# Generated by Django 3.2.5 on 2023-12-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0002_reg_tutor_reg_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessories_selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='accessories/')),
                ('accessory_type', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='craft_selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='crafts/')),
                ('craft_material', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
            ],
        ),
    ]
