# Generated by Django 3.2.5 on 2023-12-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0003_accessories_selling_craft_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories_selling',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='craft_selling',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
