# Generated by Django 4.2.5 on 2024-01-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
