# Generated by Django 4.2.5 on 2024-01-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0006_remove_cart_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=30)),
                ('proname', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
