# Generated by Django 4.2.5 on 2024-01-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0007_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='email',
            new_name='username',
        ),
    ]
