# Generated by Django 4.2.5 on 2024-01-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0008_rename_email_pay_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='craftcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
