# Generated by Django 4.2 on 2024-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0009_craftcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('video_link', models.URLField()),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
