# Generated by Django 4.2 on 2024-02-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0010_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='craftcart',
            name='category',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='totalamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='craftcart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='craftcart',
            name='totalamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
