# Generated by Django 4.2.5 on 2024-03-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0011_remove_cart_category_remove_craftcart_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
